### ISSUE TITLE
Feedback IT 02 - Testes TDD e BDD

### ISSUE THREAD

**Issue by ps1312** [ricarthlima/eo-project-es#101]
Ae pessoal, com um _pouco_ de atraso vou corrigir os testes da IT 02, considerei o estado do repositório de acordo com o período da IT 02 08/10 até 22/10.

## Testes TDD:
<ul>
  <li>Não encontrei os testes TDD de vcs</li>
</ul>

### Nota Final: 0
---------------------------------------------------------------

## Testes BDD:
<ul>
  <li>Nenhum step definition foi implementado.</li>
</ul>

### Nota Final: 0
---------------------------------------------------------------

## Nota Final Total: 0

**Comment by ricarthlima** [comment]
Cientes, obrigado.
