### ISSUE TITLE
Feedback Testes TDD e BDD IT3

### ISSUE THREAD

**Issue by joismar** [ricarthlima/eo-project-es#108]
Opa! Para esse item foram avaliados os seguintes critérios:

**Testes TDD**
- Testes rodaram: Não Completamente (-1,5)
- Coerência: Ok
- Caminhos felizes e tristes: Não (-0,5)

**Testes BDD**
- Testes rodaram: Não (-1,5)
- Coerência: Ok
- Caminhos felizes e tristes: Não (-0,5)
Obs.: Alguns erros de português (-0,5)

Nota Final: **5,5**

Qualquer dúvida estou no Telegram ;)

**Comment by ricarthlima** [comment]
Cientes, obrigado!
