### ISSUE TITLE
Organizar pasta das iterações

### ISSUE THREAD

**Issue by warleys14** [ricarthlima/eo-project-es#12]
**A funcionalidade está envolvida com um problema?**
Adaptação indicada pelo monitor na organização das pastas de entregas do repositório.

**Descreva a solução que você gostaria**
Ideia de organizar as pastas das iterações com as documentações e incluir as atas de reuniões nas pastas das iterações.

**Descreva alternativas para sua solução**
Uma maneira seria baseada no repositório do iFarra, mas pode ser bem adaptada com o que nós já temos.

**Informação adicional**
A organização das mesmas deve ser conversada com o time.

**Comment by ricarthlima** [comment]
**Entregas:**
- Os documentos agora estão na pasta /docs/
- As atas de reunião agora serão subpastas das iterações

**Adicionais:**
- README.md e Time.md atualizado com as atribuições dos papéis.
- Criada branch para GH-Pages. A página está disponível [aqui.](https://ricarthlima.github.io/eo-project-es/)
