### ISSUE TITLE
Reunião sobre I00D04 (21/09)

### ISSUE THREAD

**Issue by ricarthlima** [ricarthlima/eo-project-es#13]
# Ata de Reunião (Definição)

## Informações
**Data:** 21/09/2018
**Horário:** 16:00 - 17:00
**Local:** Bloco E
**Participantes:** Monalisa Sousa, Guilherme Prado, Ricarth Lima e Warley Souza  

## Pauta da Reunião
Perguntas do Scrum. Estudar as entregas e definir tarefas para a DeadLine 04 que acontecerá na próxima segunda. Também será discutido as tarefas que estão em aberta até então e o mapeamento dos EAs. Definir nome do software. Conversar melhor sobre os papéis.

**Comment by warleys14** [comment]
- **Todos:**
  - Pesquisar como fazer um bom postmortem /  Ver informações sobre o postmortem no site da disciplina
  - Pesquisar sobre HUs
  - Decidir sobre HUs sabado
- **Ricarth:** Digitar HU
- **Warley:** Criar grupo com monitores
-

**Comment by ricarthlima** [comment]
Ata de reunião disponível [aqui.](https://github.com/ricarthlima/eo-project-es/blob/master/docs/entregas_iterations/I00/atas_reuniao/2018_09_20_defini%C3%A7%C3%B5es.md)
