### ISSUE TITLE
Refazer entrega 01 de Banco de Dados

### ISSUE THREAD

**Issue by warleys14** [ricarthlima/eo-project-es#14]
**Definição de pronto**
Essa tarefa será concluída quando a entrega relacionada a descrição da aplicação, projeto conceitual e projeto lógico forem entregues na pasta para Bernadette com o nome "Entrega 01 - Novo".

**Informações adicionais**
Como foi dado um spin-off no projeto, e isso ocorreu depois da entrega 01 da cadeira de banco de dados, foi conversado com a professora, e ela disse que deve ser refeito e adicionado a pasta no drive novamente o mais rápido possível.

**Comment by ricarthlima** [comment]
- **Feitas (para validação)** 
  - ~Descrição do informal do minimundo~
  - ~Diagrama Entidade Relacionamento~
- **Para fazer**
  - Completar documento da descrição informal (outras perguntas)
  - Mapeamento pro modelo relacional
  - Postar no drive da professora

As alterações podem ser encontradas [aqui.](https://drive.google.com/open?id=1Lpa1a2hKlQtJNqFx5bPv88Q20CKt13zH)

**Comment by warleys14** [comment]
O link da entrega pode ser encontrado [aqui.](https://drive.google.com/drive/u/1/folders/1oBG6K-uudJRxRFzxGFmhxsP2nzS1yUrV)
