### ISSUE TITLE
Postmortem da I00

### ISSUE THREAD

**Issue by ricarthlima** [ricarthlima/eo-project-es#17]
**Definição de pronto**
Não sei o que isso deve gerar, falar com o professor.

**Comment by warleys14** [comment]
- Criar grupo com os monitores (Warley)
- Pesquisar sobre como construir um bom postmortem (Todos)
- Ver informações no site (Todos)

**Comment by Monaliisa** [comment]
Foi concluído e pode ser visto[aqui.](https://github.com/ricarthlima/eo-project-es/blob/master/docs/entregas_iterations/I00/postmortem.md)
