### ISSUE TITLE
Reunião com a Cliente (29/09 - Paula)

### ISSUE THREAD

**Issue by ricarthlima** [ricarthlima/eo-project-es#21]
# Ata de Reunião (Cliente)

## Informações
**Data:** 29/09/2018
**Horário:** 18:30
**Local:** Discord
**Participantes:** Warley Souza e Paula Vaz

## Pauta da Reunião
Nessa reunião faremos nosso primeiro contato direto com uma Early Adopter, para contextualizá-la começando com uma apresentação do time e dos seus objetivos. Depois conversaremos sobre HUs que criamos, e suas necessidades para outras HUs.

#### Ambientação com o nosso projeto
Nessa discussão foi feito uma ambientação da nossa early adopter a respeito do nosso projeto. Tal como apresentação do nosso time, explicação dos nossos spin-offs e descrição detalhada do nosso escopo atual do projeto.

#### Apresentação das HUs, storyboard, feedback e dúvidas
Nessa discussão foi abordado as nossas HUs e o storyboard (que estão aqui no nosso repositório). Além disso, Paula nos deu bastantes feedbacks, explicações do nicho (o qual ela está bem ambientada) e dicas interessantes.

## Registro das Decisões
A partir dessa reunião ficou acordado a implantação de melhorias iniciais, aprofundamento no nosso storyboard e pesquisas para esclarecimentos gerais.

## Compromissos
- **Todos:** 
  - Implantar melhorias gerais;
- **Ricarth:**
  - Ler e discutir sobre o arquivo gerado da reunião;
- **Warley**:
  - Fazer reunião e gerar documento sobre;
- **Monalisa**:
  - Ler e discutir sobre o arquivo gerado da reunião;
- **Guilherme:**
  - Ler e discutir sobre o arquivo gerado da reunião;
- **Próximas reuniões**:
  - Segunda, quarta e sexta; Bloco E, 16:00 até as 17:00.
  - Descrição da próxima reunião marcada

**Comment by warleys14** [comment]
Reunião feita e documento gerado. O mesmo pode ser encontrado através do [link.](https://docs.google.com/document/d/1EL8bR6SseofypMSdZ4qMqsO6arqbtXNCkYyUAfSBmNw/edit?usp=sharing)
