### ISSUE TITLE
[Back][HU] Tela inicial intuitiva

### ISSUE THREAD

**Issue by ricarthlima** [ricarthlima/eo-project-es#28]
**Descrição clássica da história do usuário**
Como um novo usuário do sistema, 
para que eu não tenha dificuldades em aprender a usá-lo, 
quero que ele tenha as funcionalidades principais já na primeira tela. 

**Informações adicionais**
Deve ser desenvolvido junto com a tela inicial seguindo o storyboard mais recente.

**Comment by warleys14** [comment]
A mesma já foi feita e está sendo aprimorada com feedbacks da cliente.
