### ISSUE TITLE
[Front][HU] Cadastro

### ISSUE THREAD

**Issue by ricarthlima** [ricarthlima/eo-project-es#33]
## Definição de pronto
Deverão ser feita as telas do fluxo de "Cadastro" usando HTML/CSS/Bootstrap e seguindo o modelo do mockup mais recente.

## Informações adicionais
Essa tarefa contempla as seguintes HUs

Como novo usuário, para que eu possa me registrar no sistema, eu quero não precisar inserir nenhuma informação manualmente.

Como um usuário ovolactovegetariano, para que o sistema de recomende produtos menos restritos, eu quero informar minhas características alimentares com 1 clique apenas uma vez.

Como usuário que não possui contas em serviços como Google ou Facebook, para que eu possa me registrar, eu quero que esse registro não demore mais de 30 segundos para ser preenchido.

Como um usuário que não se encaixa nas classificações principais plant-based, para que eu também seja contemplado na entrega de valor do sistema, eu quero selecionar uma categoria não específica.

**Comment by warleys14** [comment]
A mesma já está feita no MVP da aplicação
