### ISSUE TITLE
Estudar TDD com RSPEC

### ISSUE THREAD

**Issue by ricarthlima** [ricarthlima/eo-project-es#34]
## Definição de pronto
Deverá ser gerado um documento com os conhecimentos adquiridos. O delegado também deverá ser capaz de explicar para o resto da equipe os próximos passos a respeito disso.

**Comment by Monaliisa** [comment]
RSpec iniciado e teste do Model de Produtos criado. Disponível [aqui.](https://github.com/ricarthlima/eo-project-es/tree/master/spec)
