### ISSUE TITLE
Estudar BDD com CUCUMBER

### ISSUE THREAD

**Issue by ricarthlima** [ricarthlima/eo-project-es#35]
## Definição de pronto
Deverá ser gerado um documento com os conhecimentos adquiridos. A delegada também deverá ser capaz de explicar para o resto da equipe os próximos passos a respeito disso.

**Comment by Monaliisa** [comment]
Features e steps criados, pode ser verificado [aqui.](https://github.com/ricarthlima/eo-project-es/tree/master/features)
