### ISSUE TITLE
Pesquisar sobre apps com propostas similares a nossa PUV

### ISSUE THREAD

**Issue by ricarthlima** [ricarthlima/eo-project-es#4]
Gerar um documento (.md), por na pasta "documentos" (criar caso ela não exista).

**Comment by Monaliisa** [comment]
Foi feita a pesquisa. E gerei esse [documento.](https://docs.google.com/document/d/1UD-w_lUweBpu-74wSQFxDVuQ4FlVkBowqThhjBEvzrI/edit?usp=sharing)
