### ISSUE TITLE
[1.3.2.1] Pegar informação de qual usuário que está logado

### ISSUE THREAD

**Issue by warleys14** [ricarthlima/eo-project-es#53]
## Definição de pronto
Estará pronta quando estiver mapeado no banco e quando o usuário logar aparecer o nome dele na tela inicial.

## Informações adicionais
S/A

**Comment by ricarthlima** [comment]
A funcionalidade está disponível na navbar desde o merge pull request #105. Foi usado o current_user do Devise.
