### ISSUE TITLE
[7.3] Criar telas de cadastro para informações simples (trafegar a informação entre elas sem gravar no banco)

### ISSUE THREAD

**Issue by warleys14** [ricarthlima/eo-project-es#69]
## Definição de pronto
Quando as telas para informações estejam sendo passadas e os valores sendo salvos sem gravar no banco.

## Informações adicionais
S/A.

**Comment by warleys14** [comment]
Feito em partes, pois não está sendo feito entre várias telas no momento.

**Comment by ricarthlima** [comment]
Separar o cadastro em várias telas não está mais no escopo de atuação do MVP. Se necessário, reabir.
