### ISSUE TITLE
[3.1] Receber uma informação da tela inicial

### ISSUE THREAD

**Issue by warleys14** [ricarthlima/eo-project-es#87]
## Definição de pronto
Estará pronto quando o seguinte caso for satisfeito: Reconhecer se foi inserido um texto, uma imagem ou ambos, e tratar isso para chamar as telas de caso bom, caso ruim ou caso múltiplo.

## Informações adicionais
S/A.

**Comment by ricarthlima** [comment]
Feito, a tela "inicio" envia a informação recebida para o controller "busca".
