### ISSUE TITLE
[3.2.2.1] Se só houver uma com mais de 80% de semelhança, caso bom, abrir tela de descrição do Produto, Marca ou Componente

### ISSUE THREAD

**Issue by warleys14** [ricarthlima/eo-project-es#91]
## Definição de pronto
Estará pronta quando a lógica estiver feita e a tela seja mostrada adequadamente.

## Informações adicionais
S/A.

**Comment by ricarthlima** [comment]
Redirecionado para tela de "Read" do Produto/Marca/Componente que foi gerada pelo Scaffold. Precisa ser refeita.
