### ISSUE TITLE
[3.2.2.2] Se não houver apenas uma com 80% de semelhança, pegar todas com pelo menos 50% de semelhança e chamar na tela de caso múltiplo

### ISSUE THREAD

**Issue by warleys14** [ricarthlima/eo-project-es#92]
## Definição de pronto
Estará pronta quando a lógica estiver feita e a tela estiver sendo chamada.

## Informações adicionais
S/A.

**Comment by ricarthlima** [comment]
As porcentagens não foram obedecidas. Se houver mais de um Produto/Marca/Componente que contenha o nome inserido, o caso múltiplo é realizado em "buscar#index".
